### PR TITLE
Use GET to validate api resource existence

### LINKED ISSUE #92: Inconveniencies with ApiResourceExist
Currently, in order to use the `ApiResourceExist` constraint, the other microservice must have this bundle installed and properly configured (the [recipe](https://github.com/symfony/recipes-contrib/tree/main/mtarld/api-platform-ms-bundle/0.1) does not configure the `_check_resource` route).

I was asking myself if changing the [ExistenceChecker](https://github.com/mtarld/api-platform-ms-bundle/blob/b8a34b01ed1631c7f2e2f1bceb49416ec00490d5/src/ApiResource/ExistenceChecker.php#L23) into something like that is feasible:

```php
<?php

use Mtarld\ApiPlatformMsBundle\HttpClient\GenericHttpClient;
use Mtarld\ApiPlatformMsBundle\HttpClient\ReplaceableHttpClientInterface;
use Mtarld\ApiPlatformMsBundle\HttpClient\ReplaceableHttpClientTrait;
use Mtarld\ApiPlatformMsBundle\Microservice\MicroservicePool;

/**
 * @final
 */
class ExistenceChecker implements ReplaceableHttpClientInterface
{
    use ReplaceableHttpClientTrait;

    public function __construct(
        private GenericHttpClient $httpClient,
        private readonly MicroservicePool $microservices,
    ) {}

    public function iriExists(string $iri, string $microserviceName): bool
    {
        $response = $this->httpClient->request(
            $this->microservices->get($microserviceName),
            'GET',
            $iri,
        );

        return match ($response->getStatusCode()) {
            200, 203 => true,
            404 => false,
            default => throw new \RuntimeException(),
        };
    }
}
```

This has the following advantages:

- the other microservice does not depend on this bundle any more
- the whole routing/controller setup is obsolete and can be removed
- this bundle does not depend on `api_platform.iri_converter` and `api_platform.validator` any more, which allows decoupling from `api-platfom/symfony`

This has the following disadvantages:

- the other microservice must expose the `GET` endpoint for the required resource (which they probably have so that the caller gets the list of IRIs in the first place)
- the further validation of the current implementation (see [ApiResourceCheckerPayload](https://github.com/mtarld/api-platform-ms-bundle/blob/b8a34b01ed1631c7f2e2f1bceb49416ec00490d5/src/Dto/ApiResourceExistenceCheckerPayload.php#L18-L21) must be moved somewhere else (see below)
- the IRI must also be matched against a configurable regex pattern, since we do not validate we get a resouce but just a 200 status code (see below)

The last two disadvantages could be addressed in the `ApiResourceExistValidator` though, or even in a separate [compound constraint](https://symfony.com/blog/new-in-symfony-7-2-compound-constraint-improvements) in Symfony >= 7.2.

What do you think? If you are ok with this, I could file a PR.

### PR DESCRIPTION
**Pull request by Rainrider**
This PR does the following:

- adds a new existence verifier using GET requests to verify api resource existence in contrast to the current custom POST endpoint and deprecates the current existence checker
- adds a new idiomatic `ApiResourceExists` validation constraint and deprecates `ApiResourceExist`

Closes #92

### CODE REVIEW

**Comment by Rainrider** [comment]
@mtarld ~~The tests fail because of the self-deprecation (commented out in the last commit). I don't know how to proceed about that. The deprecation addresses [your comment](https://github.com/mtarld/api-platform-ms-bundle/issues/92#issuecomment-2804089174).~~ Ah, nvm, had to add a legacy group annotation. Still not sure if this is the right way to trigger the deprecation though.

**Comment by Rainrider** [comment]
@mtarld any thoughts on this?

File: src/ApiResource/ExistenceChecker.php [hunk 1]
```diff
@@ -24,43 +16,25 @@ class ExistenceChecker implements ReplaceableHttpClientInterface
...
-        /** @var ApiResourceExistenceCheckerView $checkedIris */
-        $checkedIris = $this->serializer->deserialize($response->getContent(), ApiResourceExistenceCheckerView::class, 'json');
-
-        return $checkedIris->existences;
+        return match ($response->getStatusCode()) {
+            200, 203 => true,
+            404 => false,
+            // make it throw
+            default => (bool) $response->getContent(true),
+        };
```
Comment (mtarld) [inline src/ApiResource/ExistenceChecker.php]: Let's return true if `>= 200 && < 300`. I'm not sure why we need to throw an exception.

File: src/ApiResource/ExistenceChecker.php [hunk 2]
```diff
@@ -24,43 +16,25 @@ class ExistenceChecker implements ReplaceableHttpClientInterface
 {
```
Comment (mtarld) [inline src/ApiResource/ExistenceChecker.php]: This file contains BC breaks (removing constructor arguments, renaming a method).
Maybe we should create a new service and deprecate that one?

File: src/Validator/ApiResourceExistValidator.php [hunk 3]
```diff
@@ -15,13 +15,11 @@ class_exists(\LogicException::class);
...
 
 /**
- * @final
- *
  * @psalm-suppress PropertyNotSetInConstructor
  *
  * @author Mathias Arlaud <mathias.arlaud@gmail.com>
  */
-class ApiResourceExistValidator extends ConstraintValidator
+final class ApiResourceExistValidator extends ConstraintValidator
```
Comment (mtarld) [inline src/Validator/ApiResourceExistValidator.php]: I'd create hard final in another PR

File: src/Validator/ApiResourceExist.php [hunk 4]
```diff
@@ -5,59 +5,48 @@
...
 
         parent::__construct($options, $groups, $payload);
 
-        if (!is_string($this->microservice)) {
-            throw new \TypeError(sprintf('"%s()": Expected argument $microservice to be a string, got "%s".', __METHOD__, get_debug_type($this->microservice)));
-        }
-
-        $this->message = $message ?? $this->message;
-        $this->skipOnError = $skipOnError ?? $this->skipOnError;
+        trigger_deprecation('mtarld/api-platform-ms-bundle', '2.0.0', sprintf('Use %s instead', ApiResourceExists::class));
```
Comment (mtarld) [inline src/Validator/ApiResourceExist.php]: `2.0.0` should instead be the latest 1.x version

Comment (mtarld) [inline src/Validator/ApiResourceExist.php]:
```suggestion
        trigger_deprecation('mtarld/api-platform-ms-bundle', '2.0.0', sprintf('%s is deprecated, use %s instead', ApiResourceExist::class, ApiResourceExists::class));
```

**Review by mtarld — CHANGES_REQUESTED** [review]
First round :wink:

File: src/ApiResource/ExistenceChecker.php (hunk 2 above)
Comment (Rainrider) [reply src/ApiResource/ExistenceChecker.php]: I just considered the service to be internal, because it is not exposed by its FQCN. I'll implement the new one named `ExistenceVerifier` and deprecate this one then.

I see you would like a smoother upgrade experience, so I could actually keep the old system intact (apart from deprecating it) and just add the new validator and its supporting services. We could stay on 1.x then.

File: src/ApiResource/ExistenceChecker.php (hunk 1 above)
Comment (Rainrider) [reply src/ApiResource/ExistenceChecker.php]: The exception is to support the current behaviour of `ApiResourceExist` (see `skipOnError`)

**Comment by Rainrider** [comment]
@mtarld thank your for the feedback, I hope I addressed everything. I updated the PR description.

File: tests/Validator/ApiResourceExistsValidatorTest.php [hunk 5]
```diff
@@ -0,0 +1,127 @@
...
+
+        $violations = $validator->validate($iri, new ApiResourceExists('bar'));
+
+        self::assertCount(0, $violations);
+    }
+
+    public static function provideBlankIris(): iterable
+    {
+        yield 'null' => [null];
+        yield 'empty' => [''];
```
Comment (mtarld) [inline tests/Validator/ApiResourceExistsValidatorTest.php:36]: An empty string as IRI should fail to me.

**Review by mtarld — COMMENTED** [review]
This is way better like that! Just one little comment.
Thanks @Rainrider 🙂

**Comment by mtarld** [comment]
Btw, do you have an account on SymfonyDevs slack?

File: tests/Validator/ApiResourceExistsValidatorTest.php (hunk 5 above)
Comment (Rainrider) [reply tests/Validator/ApiResourceExistsValidatorTest.php:36]: Hm. virtually all default constraint validators fall through on `null` and emptry string (except [PasswordStrengthValidator](https://github.com/symfony/symfony/blob/195f1f123d1328ef534f70e4605948049120ae73/src/Symfony/Component/Validator/Constraints/PasswordStrengthValidator.php#L35-L37)?). This was the reason I included `''`. I'll remove it then.

**Comment by Rainrider** [comment]
It appears I don't. https://symfony.com/slack appears to be inactive, so I don't know how to join.

**Comment by Rainrider** [comment]
Ah, static analysis fails now, but this is not introduced by me. I could fix this in a separate PR together with some other house keeping if you don't mind.

File: tests/Validator/ApiResourceExistsValidatorTest.php (hunk 5 above)
Comment (mtarld) [reply tests/Validator/ApiResourceExistsValidatorTest.php:36]: Yes you're right, let's keep it like that

**Comment by mtarld** [comment]
> It appears I don't. [symfony.com/slack](https://symfony.com/slack) appears to be inactive, so I don't know how to join.

Can you try with https://symfony-devs.slack.com/? Then reach me at `mtarld`

> Ah, static analysis fails now, but this is not introduced by me. I could fix this in a separate PR together with some other house keeping if you don't mind.

With pleasure!

**Review by mtarld — APPROVED** [review]

**Comment by Rainrider** [comment]
@mtarld https://symfony-devs.slack.com there is no sign-up under this link, only sign-in. I cannot create an account.

**Comment by mtarld** [comment]
Alright, then, can you reach me at my email? (Can be found in https://github.com/mtarld/api-platform-ms-bundle#authors)

**Comment by Rainrider** [comment]
I rebased on 1.x and added an override attribute to `ApiResourceExistsvalidator::validate`. This should pass the tests once #95 is merged. Alternatively you could change the target branch of this PR to `house-keeping` to test this claim.

**Review by mtarld — APPROVED** [review]
